# Generated by Django 6.0.5 on 2026-05-30 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0001_initial'),
        ('ged', '0001_initial'),
        ('programmes_projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_compte', models.CharField(choices=[('outlook', 'Microsoft Outlook / Exchange'), ('gmail', 'Gmail / Google Workspace'), ('imap', 'Serveur IMAP'), ('pop3', 'Serveur POP3')], default='imap', max_length=10)),
                ('nom_affichage', models.CharField(max_length=200)),
                ('adresse_email', models.EmailField(max_length=254)),
                ('serveur_entrant', models.CharField(blank=True, max_length=200)),
                ('port_entrant', models.IntegerField(default=993)),
                ('serveur_sortant', models.CharField(blank=True, max_length=200)),
                ('port_sortant', models.IntegerField(default=587)),
                ('ssl_entrant', models.BooleanField(default=True)),
                ('ssl_sortant', models.BooleanField(default=True)),
                ('identifiant', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('erreur', 'Erreur de connexion')], default='actif', max_length=10)),
                ('est_principal', models.BooleanField(default=False)),
                ('derniere_synchro', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte email',
                'ordering': ['nom_affichage'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('entrant', 'Entrant'), ('sortant', 'Sortant'), ('brouillon', 'Brouillon')], max_length=10)),
                ('message_id', models.CharField(blank=True, max_length=500)),
                ('sujet', models.CharField(max_length=500)),
                ('corps_html', models.TextField(blank=True)),
                ('corps_texte', models.TextField(blank=True)),
                ('expediteur', models.CharField(max_length=300)),
                ('expediteur_email', models.EmailField(max_length=254)),
                ('destinataires', models.JSONField(default=list)),
                ('destinataires_cc', models.JSONField(blank=True, default=list)),
                ('destinataires_cci', models.JSONField(blank=True, default=list)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('date_envoi_differe', models.DateTimeField(blank=True, null=True)),
                ('priorite', models.CharField(choices=[('normale', 'Normale'), ('haute', 'Haute'), ('basse', 'Basse')], default='normale', max_length=10)),
                ('statut', models.CharField(choices=[('non_lu', 'Non lu'), ('lu', 'Lu'), ('repondu', 'Répondu'), ('transfiere', 'Transféré'), ('archive', 'Archivé'), ('supprime', 'Supprimé'), ('spam', 'Spam')], default='non_lu', max_length=15)),
                ('est_lu', models.BooleanField(default=False)),
                ('lu_le', models.DateTimeField(blank=True, null=True)),
                ('thread_id', models.CharField(blank=True, max_length=300)),
                ('resume_ia', models.TextField(blank=True)),
                ('actions_detectees', models.JSONField(blank=True, default=list)),
                ('echeances_detectees', models.JSONField(blank=True, default=list)),
                ('categorie_ia', models.CharField(blank=True, max_length=200)),
                ('score_urgence', models.IntegerField(default=0)),
                ('risques_detectes', models.JSONField(blank=True, default=list)),
                ('traite_par_ia', models.BooleanField(default=False)),
                ('archive_ged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='execution.activiteexecution')),
                ('compte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='courrier_intelligent.compteemail')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_geres', to=settings.AUTH_USER_MODEL)),
                ('document_ged', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='ged.document')),
                ('en_reponse_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='courrier_intelligent.email')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='programmes_projets.projet')),
                ('reunion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='execution.reunion')),
            ],
            options={
                'verbose_name': 'Email',
                'ordering': ['-date_reception', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('tache', 'Tâche'), ('activite', 'Activité'), ('reunion', 'Réunion'), ('livrable', 'Livrable'), ('courrier', 'Courrier administratif'), ('incident', 'Incident')], default='tache', max_length=15)),
                ('description', models.TextField()),
                ('echeance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('detectee', 'Détectée'), ('validee', 'Validée'), ('convertie', 'Convertie'), ('ignoree', 'Ignorée')], default='detectee', max_length=15)),
                ('detectee_par_ia', models.BooleanField(default=True)),
                ('objet_genere_id', models.IntegerField(blank=True, null=True)),
                ('objet_genere_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_email', to=settings.AUTH_USER_MODEL)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_emails', to='courrier_intelligent.email')),
            ],
            options={
                'verbose_name': 'Action email',
                'ordering': ['echeance'],
            },
        ),
        migrations.CreateModel(
            name='EtiquetteEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('couleur', models.CharField(default='#3388ff', max_length=7)),
                ('emails', models.ManyToManyField(blank=True, related_name='etiquettes', to='courrier_intelligent.email')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquettes_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Étiquette email',
            },
        ),
        migrations.CreateModel(
            name='PieceJointeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=300)),
                ('type_mime', models.CharField(blank=True, max_length=100)),
                ('taille', models.BigIntegerField(default=0)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='emails/pj/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_ged', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pj_emails', to='ged.document')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='courrier_intelligent.email')),
            ],
            options={
                'verbose_name': 'Pièce jointe email',
            },
        ),
    ]
