# Generated by Django 6.0.5 on 2026-05-31 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier_intelligent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='suggestion_reponse_ia',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='RegleClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('priorite', models.IntegerField(default=0, help_text="Ordre d'application (plus petit = plus prioritaire)")),
                ('operateur', models.CharField(choices=[('et', 'Toutes les conditions (ET)'), ('ou', 'Au moins une condition (OU)')], default='et', max_length=5)),
                ('conditions', models.JSONField(default=list, help_text='[{"champ": "sujet", "operateur": "contient", "valeur": "urgent"}]')),
                ('action', models.CharField(choices=[('etiqueter', 'Ajouter une étiquette'), ('classer_projet', 'Classer dans un projet'), ('classer_programme', 'Classer dans un programme'), ('marquer_urgent', 'Marquer comme urgent'), ('archiver', 'Archiver automatiquement'), ('notifier', 'Envoyer une notification'), ('assigner_ia', 'Déclencher analyse IA')], default='etiqueter', max_length=20)),
                ('parametres_action', models.JSONField(blank=True, default=dict, help_text='{"etiquette_id": 1} ou {"projet_id": 5}')),
                ('nb_applications', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regles_classification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Règle de classification',
                'ordering': ['priorite', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='SignatureEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('contenu_html', models.TextField(blank=True)),
                ('contenu_texte', models.TextField(blank=True)),
                ('est_principale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='courrier_intelligent.compteemail')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signature email',
                'ordering': ['-est_principale', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TemplateReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('type_template', models.CharField(choices=[('accusé_reception', 'Accusé de réception'), ('demande_info', "Demande d'informations complémentaires"), ('validation', 'Validation / Accord'), ('refus', 'Refus / Rejet'), ('transmission', 'Transmission / Transfert'), ('relance', 'Relance'), ('convocation', 'Convocation à réunion'), ('autre', 'Autre')], default='autre', max_length=25)),
                ('sujet_template', models.CharField(blank=True, help_text="Modèle de sujet. Utilisez {{sujet_original}} pour inclure le sujet d'origine.", max_length=500)),
                ('corps_html', models.TextField(blank=True)),
                ('corps_texte', models.TextField()),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('ar', 'Arabe')], default='fr', max_length=5)),
                ('variables', models.JSONField(blank=True, default=list, help_text="Variables disponibles dans ce template, ex: ['nom_destinataire', 'date']")),
                ('est_global', models.BooleanField(default=False, help_text='Accessible à tous les utilisateurs')),
                ('nb_utilisations', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_email_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de réponse',
                'ordering': ['type_template', 'titre'],
            },
        ),
    ]
