# Generated by Django 6.0.5 on 2026-05-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier_intelligent', '0002_add_missing_email_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteemail',
            name='mot_de_passe',
            field=models.CharField(blank=True, help_text='Mot de passe ou App Password (stocké chiffré en production)', max_length=500),
        ),
    ]
