# Generated by Django 6.0.5 on 2026-05-31 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier_intelligent', '0003_add_mot_de_passe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LienEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet_type', models.CharField(choices=[('courrier_entrant', 'Courrier entrant'), ('courrier_sortant', 'Courrier sortant'), ('diligence', 'Diligence'), ('reunion', 'Réunion'), ('tache', 'Tâche')], max_length=20)),
                ('objet_id', models.PositiveIntegerField()),
                ('objet_libelle', models.CharField(blank=True, max_length=300)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liens_emails', to=settings.AUTH_USER_MODEL)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens', to='courrier_intelligent.email')),
            ],
            options={
                'verbose_name': 'Lien email',
                'unique_together': {('email', 'objet_type', 'objet_id')},
            },
        ),
    ]
