# Generated by Django 6.0.5 on 2026-05-30 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0001_initial'),
        ('programmes_projets', '0001_initial'),
        ('suivi_evaluation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointageTerrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pointage', models.CharField(choices=[('presence', 'Présence'), ('mission', 'Mission'), ('visite', 'Visite terrain'), ('controle', 'Contrôle'), ('audit', 'Audit')], default='presence', max_length=15)),
                ('date_heure', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precision_gps', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('adresse_geo', models.CharField(blank=True, max_length=500)),
                ('photo_preuve', models.ImageField(blank=True, null=True, upload_to='terrain/pointages/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('valide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages', to='execution.activiteexecution')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages_terrain', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages', to='programmes_projets.projet')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pointage terrain',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='QRCodeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_qr', models.TextField()),
                ('type_objet', models.CharField(blank=True, max_length=50)),
                ('objet_id', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_scan', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan QR Code',
                'ordering': ['-date_scan'],
            },
        ),
        migrations.CreateModel(
            name='SessionTerrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appareil', models.CharField(blank=True, max_length=200)),
                ('version_app', models.CharField(blank=True, max_length=20)),
                ('mode_hors_ligne', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('synchronisee', 'Synchronisée'), ('erreur', 'Erreur de synchronisation')], default='en_cours', max_length=20)),
                ('latitude_debut', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude_debut', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude_fin', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude_fin', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('nb_collectes', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_terrain', to='execution.activiteexecution')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_terrain', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_terrain', to='programmes_projets.projet')),
            ],
            options={
                'verbose_name': 'Session terrain',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='CollecteTerrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_collecte', models.CharField(choices=[('formulaire', 'Formulaire'), ('photo', 'Photo'), ('video', 'Vidéo'), ('audio', 'Audio'), ('observation', 'Observation'), ('interview', 'Interview'), ('mesure', 'Mesure')], default='observation', max_length=15)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('donnees', models.JSONField(blank=True, default=dict)),
                ('valeur_numerique', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('fichier_media', models.FileField(blank=True, null=True, upload_to='terrain/media/%Y/%m/')),
                ('type_mime', models.CharField(blank=True, max_length=100)),
                ('taille_fichier', models.BigIntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precision_gps', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('adresse_geo', models.CharField(blank=True, max_length=500)),
                ('statut', models.CharField(choices=[('local', 'Stocké localement'), ('en_attente_sync', 'En attente de synchronisation'), ('synchronise', 'Synchronisé'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='local', max_length=20)),
                ('date_collecte_locale', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formulaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_terrain', to='suivi_evaluation.formulairedynamique')),
                ('indicateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_terrain', to='suivi_evaluation.indicateur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_terrain_validees', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectes', to='mobile_terrain.sessionterrain')),
            ],
            options={
                'verbose_name': 'Collecte terrain',
                'ordering': ['-date_collecte_locale'],
            },
        ),
        migrations.CreateModel(
            name='SynchronisationMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_synchro', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('succes', 'Succès'), ('partiel', 'Partiel'), ('echec', 'Échec')], default='succes', max_length=10)),
                ('nb_elements_envoyes', models.IntegerField(default=0)),
                ('nb_elements_recus', models.IntegerField(default=0)),
                ('nb_erreurs', models.IntegerField(default=0)),
                ('duree_secondes', models.IntegerField(default=0)),
                ('version_app', models.CharField(blank=True, max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('message_erreur', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synchronisations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Synchronisation mobile',
                'ordering': ['-date_synchro'],
            },
        ),
    ]
