# Generated by Django 6.0.5 on 2026-05-31 02:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0001_initial'),
        ('programmes_projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unite', models.CharField(choices=[('piece', 'Pièce'), ('kg', 'Kilogramme'), ('litre', 'Litre'), ('boite', 'Boîte'), ('carton', 'Carton'), ('rame', 'Rame'), ('autre', 'Autre')], default='piece', max_length=10)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('stock_alerte', models.DecimalField(decimal_places=2, default=0, help_text='Seuil de réapprovisionnement', max_digits=12)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Article stock',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_inventaire', models.CharField(blank=True, max_length=30, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('type_equipement', models.CharField(choices=[('informatique', 'Informatique'), ('bureau', 'Mobilier de bureau'), ('terrain', 'Matériel terrain'), ('communication', 'Communication'), ('vehicule', 'Véhicule'), ('autre', 'Autre')], default='informatique', max_length=20)),
                ('marque', models.CharField(blank=True, max_length=100)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('affecte', 'Affecté'), ('en_reparation', 'En réparation'), ('hors_service', 'Hors service'), ('perdu', 'Perdu'), ('reforme', 'Réformé')], default='disponible', max_length=15)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('date_acquisition', models.DateField(blank=True, null=True)),
                ('valeur_acquisition', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_fin_garantie', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='logistique/equipements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affecte_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements_affectes', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='programmes_projets.projet')),
            ],
            options={
                'verbose_name': 'Équipement',
                'ordering': ['type_equipement', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magasins', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magasins', to='programmes_projets.projet')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magasins_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Magasin',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('transfert', 'Transfert'), ('inventaire', 'Ajustement inventaire'), ('perte', 'Perte/Détérioration')], max_length=15)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valeur_totale', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reference_document', models.CharField(blank=True, max_length=100)),
                ('motif', models.TextField(blank=True)),
                ('date_mouvement', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='logistique.articlestock')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL)),
                ('magasin_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_entree', to='logistique.magasin')),
                ('magasin_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_sortie', to='logistique.magasin')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='programmes_projets.projet')),
            ],
            options={
                'verbose_name': 'Mouvement stock',
                'ordering': ['-date_mouvement', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=30, unique=True)),
                ('type_vehicule', models.CharField(choices=[('voiture', 'Voiture'), ('4x4', '4x4 / SUV'), ('moto', 'Moto'), ('camion', 'Camion'), ('minibus', 'Minibus'), ('bateau', 'Bateau')], default='voiture', max_length=10)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('couleur', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_mission', 'En mission'), ('en_entretien', 'En entretien'), ('en_panne', 'En panne'), ('reforme', 'Réformé'), ('loue', 'Loué')], default='disponible', max_length=15)),
                ('kilometrage_actuel', models.IntegerField(default=0)),
                ('date_acquisition', models.DateField(blank=True, null=True)),
                ('valeur_acquisition', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_expiration_assurance', models.DateField(blank=True, null=True)),
                ('date_expiration_vignette', models.DateField(blank=True, null=True)),
                ('date_prochain_entretien', models.DateField(blank=True, null=True)),
                ('km_prochain_entretien', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='programmes_projets.projet')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'ordering': ['immatriculation'],
            },
        ),
        migrations.CreateModel(
            name='MissionVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=300)),
                ('lieu_depart', models.CharField(max_length=200)),
                ('lieu_arrivee', models.CharField(max_length=200)),
                ('date_depart', models.DateTimeField()),
                ('date_retour_prevue', models.DateTimeField(blank=True, null=True)),
                ('date_retour_reelle', models.DateTimeField(blank=True, null=True)),
                ('km_depart', models.IntegerField(default=0)),
                ('km_retour', models.IntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=15)),
                ('carburant_litres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cout_carburant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_vehicule', to='execution.activiteexecution')),
                ('autorise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_autorisees', to=settings.AUTH_USER_MODEL)),
                ('conducteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_vehicule', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_vehicule', to='programmes_projets.projet')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='logistique.vehicule')),
            ],
            options={
                'verbose_name': 'Mission véhicule',
                'ordering': ['-date_depart'],
            },
        ),
        migrations.CreateModel(
            name='EntretienVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entretien', models.CharField(choices=[('vidange', 'Vidange'), ('revision', 'Révision'), ('reparation', 'Réparation'), ('controle_technique', 'Contrôle technique'), ('pneumatiques', 'Pneumatiques'), ('autre', 'Autre')], default='revision', max_length=20)),
                ('description', models.TextField()),
                ('date_entretien', models.DateField()),
                ('km_entretien', models.IntegerField(blank=True, null=True)),
                ('prestataire', models.CharField(blank=True, max_length=200)),
                ('cout', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prochaine_echeance_date', models.DateField(blank=True, null=True)),
                ('prochaine_echeance_km', models.IntegerField(blank=True, null=True)),
                ('facture', models.FileField(blank=True, null=True, upload_to='logistique/entretiens/%Y/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens_saisis', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='logistique.vehicule')),
            ],
            options={
                'verbose_name': 'Entretien véhicule',
                'ordering': ['-date_entretien'],
            },
        ),
        migrations.CreateModel(
            name='LigneStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valeur_totale', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_stock', to='logistique.articlestock')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_stock', to='logistique.magasin')),
            ],
            options={
                'verbose_name': 'Ligne stock',
                'unique_together': {('magasin', 'article')},
            },
        ),
    ]
