# Generated by Django 6.0.5 on 2026-05-31 02:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0001_initial'),
        ('programmes_projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=30, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('type_personnel', models.CharField(choices=[('employe', 'Employé permanent'), ('consultant', 'Consultant'), ('volontaire', 'Volontaire'), ('expert', 'Expert international'), ('stagiaire', 'Stagiaire')], default='employe', max_length=15)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('conge', 'En congé'), ('mission', 'En mission')], default='actif', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('poste', models.CharField(blank=True, max_length=200)),
                ('specialite', models.CharField(blank=True, max_length=200)),
                ('niveau_expertise', models.CharField(choices=[('junior', 'Junior'), ('intermediaire', 'Intermédiaire'), ('senior', 'Senior'), ('expert', 'Expert')], default='intermediaire', max_length=20)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('date_fin_contrat', models.DateField(blank=True, null=True)),
                ('taux_journalier', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('devise', models.CharField(default='XOF', max_length=5)),
                ('taux_occupation_max', models.IntegerField(default=100)),
                ('competences', models.JSONField(blank=True, default=list)),
                ('cv', models.FileField(blank=True, null=True, upload_to='rh/cv/%Y/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rh/photos/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employe_profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employé projet',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='BesoinFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('domaine', models.CharField(blank=True, max_length=200)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('critique', 'Critique')], default='normale', max_length=10)),
                ('statut', models.CharField(choices=[('identifie', 'Identifié'), ('valide', 'Validé'), ('planifie', 'Planifié'), ('realise', 'Réalisé'), ('annule', 'Annulé')], default='identifie', max_length=15)),
                ('date_souhaitee', models.DateField(blank=True, null=True)),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('cout_estime', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cout_reel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('duree_jours', models.IntegerField(default=1)),
                ('organisme_formation', models.CharField(blank=True, max_length=300)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('attestation', models.FileField(blank=True, null=True, upload_to='rh/formations/%Y/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='besoins_formation_identifies', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='besoins_formation', to='programmes_projets.projet')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besoins_formation', to='rh_projet.employeprojet')),
            ],
            options={
                'verbose_name': 'Besoin de formation',
                'ordering': ['-priorite', 'date_souhaitee'],
            },
        ),
        migrations.CreateModel(
            name='AffectationRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('taux_affectation', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('terminee', 'Terminée'), ('suspendue', 'Suspendue'), ('annulee', 'Annulée')], default='active', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_rh', to='execution.activiteexecution')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_rh_creees', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_rh', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_rh', to='programmes_projets.projet')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='rh_projet.employeprojet')),
            ],
            options={
                'verbose_name': 'Affectation RH',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('semestrielle', 'Semestrielle'), ('annuelle', 'Annuelle')], default='annuelle', max_length=15)),
                ('annee', models.IntegerField()),
                ('trimestre', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours'), ('soumise', 'Soumise'), ('validee', 'Validée')], default='brouillon', max_length=15)),
                ('note_globale', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('criteres', models.JSONField(blank=True, default=dict)),
                ('points_forts', models.TextField(blank=True)),
                ('axes_amelioration', models.TextField(blank=True)),
                ('objectifs_periode_suivante', models.TextField(blank=True)),
                ('commentaire_employe', models.TextField(blank=True)),
                ('date_evaluation', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='rh_projet.employeprojet')),
                ('evaluateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_effectuees', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_rh', to='programmes_projets.projet')),
            ],
            options={
                'verbose_name': 'Évaluation de performance',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='FeuilleTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('annee', models.IntegerField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='brouillon', max_length=15)),
                ('total_heures', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_jours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feuilles_temps', to='rh_projet.employeprojet')),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feuilles_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feuille de temps',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('employe', 'mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='LigneFeuilleTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heures', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('description', models.CharField(blank=True, max_length=300)),
                ('est_jour_ferie', models.BooleanField(default=False)),
                ('est_conge', models.BooleanField(default=False)),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_feuille_temps', to='execution.activiteexecution')),
                ('feuille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='rh_projet.feuilletemps')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_feuille_temps', to='programmes_projets.projet')),
            ],
            options={
                'verbose_name': 'Ligne feuille de temps',
                'ordering': ['date'],
            },
        ),
    ]
