# Generated by Django 6.0.5 on 2026-06-13 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_projet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_absence', models.CharField(choices=[('autorisation', "Autorisation d'absence"), ('absence_injustifiee', 'Absence injustifiée'), ('absence_justifiee', 'Absence justifiée'), ('retard', 'Retard'), ('mission', 'Absence pour mission'), ('formation', 'Absence pour formation'), ('autre', 'Autre')], default='autorisation', max_length=25)),
                ('date_absence', models.DateField()),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('duree_heures', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('motif', models.TextField()),
                ('piece_justificative', models.FileField(blank=True, null=True, upload_to='rh/absences/%Y/')),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée'), ('annulee', 'Annulée')], default='soumise', max_length=15)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_approuvees', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_absence', to='rh_projet.employeprojet')),
            ],
            options={
                'verbose_name': "Demande d'absence",
                'verbose_name_plural': "Demandes d'absence",
                'ordering': ['-date_absence'],
            },
        ),
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('annuel', 'Congé annuel'), ('maladie', 'Congé maladie'), ('maternite', 'Congé maternité'), ('paternite', 'Congé paternité'), ('exceptionnel', 'Congé exceptionnel'), ('sans_solde', 'Congé sans solde'), ('recuperation', 'Récupération'), ('autre', 'Autre')], default='annuel', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_jours', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('motif', models.TextField(blank=True)),
                ('piece_justificative', models.FileField(blank=True, null=True, upload_to='rh/conges/%Y/')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée'), ('annulee', 'Annulée')], default='brouillon', max_length=15)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_approuves', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_conge', to='rh_projet.employeprojet')),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congé',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OccurrenceSpeciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_occurrence', models.CharField(choices=[('naissance', 'Naissance'), ('deces_conjoint', 'Décès conjoint'), ('deces_enfant', 'Décès enfant'), ('deces_parent', 'Décès parent'), ('mariage', 'Mariage'), ('maladie_grave', 'Maladie grave'), ('accident', 'Accident de travail'), ('autre', 'Autre')], max_length=20)),
                ('date_evenement', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('jours_accordes', models.IntegerField(default=0)),
                ('date_debut_conge', models.DateField(blank=True, null=True)),
                ('date_fin_conge', models.DateField(blank=True, null=True)),
                ('piece_justificative', models.FileField(blank=True, null=True, upload_to='rh/occurrences/%Y/')),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='soumise', max_length=15)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences_speciales', to='rh_projet.employeprojet')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Occurrence spéciale',
                'verbose_name_plural': 'Occurrences spéciales',
                'ordering': ['-date_evenement'],
            },
        ),
    ]
