# Generated by Django 6.0.5 on 2026-05-30 21:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ged', '0001_initial'),
        ('programmes_projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Circuit de validation',
            },
        ),
        migrations.CreateModel(
            name='CourrierEntrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30)),
                ('date_reception', models.DateField()),
                ('expediteur', models.CharField(max_length=300)),
                ('organisation_expediteur', models.CharField(blank=True, max_length=300)),
                ('email_expediteur', models.EmailField(blank=True, max_length=254)),
                ('objet', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('urgence', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('tres_urgent', 'Très urgent')], default='normal', max_length=15)),
                ('canal', models.CharField(choices=[('papier', 'Papier / Dépôt physique'), ('email', 'Email'), ('portail', 'Portail'), ('fax', 'Fax')], default='papier', max_length=10)),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('affecte', 'Affecté'), ('en_cours', 'En cours de traitement'), ('traite', 'Traité'), ('cloture', 'Clôturé'), ('archive', 'Archivé')], default='recu', max_length=15)),
                ('fichier_scan', models.FileField(blank=True, null=True, upload_to='courriers/entrants/%Y/%m/')),
                ('ocr_effectue', models.BooleanField(default=False)),
                ('texte_ocr', models.TextField(blank=True)),
                ('date_affectation', models.DateTimeField(blank=True, null=True)),
                ('instruction_affectation', models.TextField(blank=True)),
                ('date_traitement', models.DateField(blank=True, null=True)),
                ('reponse_donnee', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affecte_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_affectes', to=settings.AUTH_USER_MODEL)),
                ('document_ged', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_entrants', to='ged.document')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_enregistres', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_entrants', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_entrants', to='programmes_projets.projet')),
            ],
            options={
                'verbose_name': 'Courrier entrant',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='CourrierSortant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30)),
                ('type_courrier', models.CharField(choices=[('lettre', 'Lettre'), ('note_service', 'Note de service'), ('decision', 'Décision'), ('circulaire', 'Circulaire'), ('correspondance', 'Correspondance partenaire'), ('rapport', 'Rapport'), ('autre', 'Autre')], default='lettre', max_length=20)),
                ('objet', models.CharField(max_length=500)),
                ('corps', models.TextField(blank=True)),
                ('destinataire', models.CharField(max_length=300)),
                ('organisation_destinataire', models.CharField(blank=True, max_length=300)),
                ('email_destinataire', models.EmailField(blank=True, max_length=254)),
                ('date_courrier', models.DateField(default=django.utils.timezone.now)),
                ('date_expedition', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_validation', 'En validation'), ('valide', 'Validé'), ('signe', 'Signé'), ('expedie', 'Expédié'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='courriers/sortants/%Y/%m/')),
                ('modele_utilise', models.CharField(blank=True, max_length=50)),
                ('date_signature', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_ged', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_sortants', to='ged.document')),
                ('en_reponse_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='courrier_administratif.courrierentrant')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_sortants', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_sortants', to='programmes_projets.projet')),
                ('redacteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_rediges', to=settings.AUTH_USER_MODEL)),
                ('signataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_signes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Courrier sortant',
                'ordering': ['-date_courrier'],
            },
        ),
        migrations.CreateModel(
            name='Diligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_diligence', models.CharField(choices=[('tache', 'Tâche'), ('activite', 'Activité'), ('action', 'Action'), ('decision', 'Décision')], default='action', max_length=15)),
                ('description', models.TextField()),
                ('echeance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours'), ('realisee', 'Réalisée'), ('cloturee', 'Clôturée'), ('annulee', 'Annulée')], default='ouverte', max_length=15)),
                ('resultat', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigne_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diligences_assignees', to=settings.AUTH_USER_MODEL)),
                ('courrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diligences', to='courrier_administratif.courrierentrant')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diligences_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diligence',
                'ordering': ['echeance'],
            },
        ),
        migrations.CreateModel(
            name='EtapeCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField()),
                ('nom_etape', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('obligatoire', models.BooleanField(default=True)),
                ('delai_jours', models.IntegerField(default=2)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='courrier_administratif.circuitvalidation')),
                ('validateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_validation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Étape circuit',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Parapheur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30)),
                ('intitule', models.CharField(max_length=300)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('signe', 'Signé'), ('archive', 'Archivé')], default='en_cours', max_length=15)),
                ('etape_courante', models.IntegerField(default=1)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('circuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parapheurs', to='courrier_administratif.circuitvalidation')),
                ('courrier_sortant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parapheur', to='courrier_administratif.courriersortant')),
                ('document_ged', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parapheurs', to='ged.document')),
                ('soumis_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parapheurs_soumis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parapheur',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='VisaParapheur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(default=0)),
                ('decision', models.CharField(choices=[('valide', 'Validé / Visé'), ('rejete', 'Rejeté'), ('commente', 'Commenté'), ('signe', 'Signé'), ('en_attente', 'En attente')], default='en_attente', max_length=15)),
                ('commentaire', models.TextField(blank=True)),
                ('date_visa', models.DateTimeField(blank=True, null=True)),
                ('delai_prevu', models.DateField(blank=True, null=True)),
                ('etape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visas', to='courrier_administratif.etapecircuit')),
                ('parapheur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visas', to='courrier_administratif.parapheur')),
                ('validateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visas_donnes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visa parapheur',
                'ordering': ['ordre'],
            },
        ),
    ]
