# Generated by Django 6.0.5 on 2026-06-01 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier_administratif', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleCourrierSortant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_courrier', models.CharField(choices=[('lettre', 'Lettre'), ('note_service', 'Note de service'), ('decision', 'Décision'), ('circulaire', 'Circulaire'), ('correspondance', 'Correspondance partenaire'), ('rapport', 'Rapport'), ('autre', 'Autre')], default='lettre', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('objet', models.CharField(blank=True, max_length=300)),
                ('corps', models.TextField(blank=True, help_text='Corps du modèle avec variables {{nom_destinataire}}, {{date}}, etc.')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modeles_courrier_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modèle de courrier',
                'ordering': ['type_courrier', 'nom'],
            },
        ),
    ]
