# Generated by Django 6.0.5 on 2026-06-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_qualite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionqualite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditinterne',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='indicateurqualite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nonconformite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
