# Generated by Django 6.0.5 on 2026-05-31 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ged', '0001_initial'),
        ('programmes_projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntreeBibliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('categorie', models.CharField(choices=[('guide', 'Guide / Manuel'), ('rapport', 'Rapport'), ('etude', 'Étude / Recherche'), ('outil', 'Outil / Template'), ('formation', 'Support de formation'), ('reference', 'Document de référence'), ('article', 'Article / Publication'), ('autre', 'Autre')], default='guide', max_length=20)),
                ('sous_categorie', models.CharField(blank=True, max_length=100)),
                ('domaine', models.CharField(choices=[('gestion_projet', 'Gestion de projet'), ('suivi_evaluation', 'Suivi-évaluation'), ('finance', 'Finance / Comptabilité'), ('rh', 'Ressources humaines'), ('juridique', 'Juridique'), ('logistique', 'Logistique'), ('communication', 'Communication'), ('technique', 'Technique'), ('participation', 'Participation communautaire'), ('gouvernance', 'Gouvernance'), ('autre', 'Autre')], default='gestion_projet', max_length=25)),
                ('description', models.TextField(blank=True)),
                ('auteur', models.CharField(blank=True, max_length=200)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('annee_publication', models.IntegerField(blank=True, null=True)),
                ('langue', models.CharField(default='fr', max_length=5)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='capitalisation/bibliotheque/%Y/')),
                ('url_externe', models.URLField(blank=True)),
                ('mots_cles', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('est_public', models.BooleanField(default=True)),
                ('nb_telechargements', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_ajoutees', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_bibliotheque', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_bibliotheque', to='programmes_projets.projet')),
            ],
            options={
                'verbose_name': 'Entrée bibliothèque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FicheCapitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20)),
                ('titre', models.CharField(max_length=300)),
                ('type_fiche', models.CharField(choices=[('bonne_pratique', 'Bonne pratique'), ('retour_experience', "Retour d'expérience"), ('lecon_apprise', 'Leçon apprise'), ('etude_cas', 'Étude de cas'), ('innovation', 'Innovation'), ('echec_analyse', 'Échec analysé')], default='lecon_apprise', max_length=20)),
                ('domaine', models.CharField(choices=[('gestion_projet', 'Gestion de projet'), ('suivi_evaluation', 'Suivi-évaluation'), ('finance', 'Finance / Comptabilité'), ('rh', 'Ressources humaines'), ('juridique', 'Juridique'), ('logistique', 'Logistique'), ('communication', 'Communication'), ('technique', 'Technique'), ('participation', 'Participation communautaire'), ('gouvernance', 'Gouvernance'), ('autre', 'Autre')], default='gestion_projet', max_length=25)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('validee', 'Validée'), ('publiee', 'Publiée'), ('archivee', 'Archivée')], default='brouillon', max_length=15)),
                ('contexte', models.TextField(blank=True)),
                ('probleme_defi', models.TextField(blank=True)),
                ('solution_approche', models.TextField()),
                ('resultats_obtenus', models.TextField(blank=True)),
                ('lecon_principale', models.TextField()),
                ('recommandation', models.TextField(blank=True)),
                ('conditions_replicabilite', models.TextField(blank=True)),
                ('indicateurs_succes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('mots_cles', models.TextField(blank=True)),
                ('niveau_replicabilite', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé')], default='moyen', max_length=20)),
                ('periode_reference', models.CharField(blank=True, max_length=100)),
                ('zone_geographique', models.CharField(blank=True, max_length=200)),
                ('public_cible', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('fichier_principal', models.FileField(blank=True, null=True, upload_to='capitalisation/fiches/%Y/')),
                ('genere_par_ia', models.BooleanField(default=False)),
                ('nb_consultations', models.IntegerField(default=0)),
                ('nb_favoris', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_capitalisation', to=settings.AUTH_USER_MODEL)),
                ('contributeurs', models.ManyToManyField(blank=True, related_name='fiches_contribuees', to=settings.AUTH_USER_MODEL)),
                ('document_ged', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_capitalisation', to='ged.document')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_capitalisation', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_capitalisation', to='programmes_projets.projet')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiche de capitalisation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireFiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaires_capitalisation', to=settings.AUTH_USER_MODEL)),
                ('en_reponse_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='capitalisation.commentairefiche')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='capitalisation.fichecapitalisation')),
            ],
            options={
                'verbose_name': 'Commentaire fiche capitalisation',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CentreConnaissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('domaine', models.CharField(choices=[('gestion_projet', 'Gestion de projet'), ('suivi_evaluation', 'Suivi-évaluation'), ('finance', 'Finance / Comptabilité'), ('rh', 'Ressources humaines'), ('juridique', 'Juridique'), ('logistique', 'Logistique'), ('communication', 'Communication'), ('technique', 'Technique'), ('participation', 'Participation communautaire'), ('gouvernance', 'Gouvernance'), ('autre', 'Autre')], default='gestion_projet', max_length=25)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('couleur', models.CharField(default='#7e22ce', max_length=7)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centres_connaissance', to=settings.AUTH_USER_MODEL)),
                ('entrees_bibliotheque', models.ManyToManyField(blank=True, related_name='centres_connaissance', to='capitalisation.entreebibliotheque')),
                ('fiches', models.ManyToManyField(blank=True, related_name='centres_connaissance', to='capitalisation.fichecapitalisation')),
            ],
            options={
                'verbose_name': 'Centre de connaissances',
                'ordering': ['domaine', 'nom'],
            },
        ),
    ]
