# Generated by Django 6.0.5 on 2026-06-13 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diligences', '0002_alter_diligence_id_alter_relancediligence_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireDiligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='diligences/commentaires/')),
                ('nom_fichier', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaires_diligences', to=settings.AUTH_USER_MODEL)),
                ('diligence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='diligences.diligence')),
            ],
            options={
                'verbose_name': 'Commentaire diligence',
                'ordering': ['created_at'],
            },
        ),
    ]
