# Generated by Django 6.0.5 on 2026-05-30 14:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matricule', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('telephone_mobile', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_profil/')),
                ('langue', models.CharField(default='fr', max_length=5)),
                ('poste', models.CharField(blank=True, max_length=200)),
                ('fonction', models.CharField(blank=True, max_length=200)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_method', models.CharField(choices=[('none', 'Aucune'), ('email', 'OTP Email'), ('sms', 'OTP SMS'), ('totp_google', 'Google Authenticator'), ('totp_microsoft', 'Microsoft Authenticator')], default='none', max_length=20)),
                ('mfa_secret', models.CharField(blank=True, max_length=64)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation'), ('export', 'Export'), ('import', 'Import'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('permission_change', 'Changement permission'), ('password_change', 'Changement mot de passe'), ('account_locked', 'Compte verrouillé'), ('account_unlocked', 'Compte déverrouillé'), ('mfa_enabled', 'MFA activé'), ('mfa_disabled', 'MFA désactivé')], max_length=20)),
                ('module', models.CharField(blank=True, max_length=30)),
                ('objet_type', models.CharField(blank=True, max_length=100)),
                ('objet_id', models.CharField(blank=True, max_length=50)),
                ('objet_repr', models.CharField(blank=True, max_length=200)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_tente', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('resultat', models.CharField(choices=[('success', 'Succès'), ('failed', 'Échec'), ('locked', 'Compte verrouillé'), ('mfa_required', 'MFA requis'), ('mfa_failed', 'Échec MFA')], max_length=15)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tentative de connexion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_device', models.CharField(choices=[('totp', 'TOTP Authenticator'), ('email', 'OTP Email'), ('sms', 'OTP SMS')], max_length=10)),
                ('secret', models.CharField(max_length=64)),
                ('confirmed', models.BooleanField(default=False)),
                ('backup_codes', models.JSONField(default=list)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dispositif MFA',
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('type_otp', models.CharField(choices=[('login_mfa', 'MFA Connexion'), ('password_reset', 'Réinitialisation MDP'), ('email_verify', 'Vérification email')], max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Code OTP',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token réinitialisation',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('gouvernance', 'Gouvernance & Administration'), ('programmes_projets', 'Programmes & Projets'), ('planification', 'Planification'), ('execution', 'Exécution'), ('suivi_evaluation', 'Suivi-Évaluation'), ('finances', 'Gestion Financière'), ('ged', 'GED & Archivage'), ('courrier_intelligent', 'Courrier Intelligent'), ('courrier_administratif', 'Courrier Administratif'), ('collaboration', 'Collaboration'), ('mobile', 'Mobile Terrain'), ('ia', 'Intelligence Artificielle'), ('bi', 'Business Intelligence'), ('marches_publics', 'Marchés Publics'), ('rh', 'RH Projet'), ('logistique', 'Logistique'), ('partenaires', 'Partenaires & Bailleurs'), ('sig', 'SIG'), ('capitalisation', 'Capitalisation')], max_length=30)),
                ('peut_lire', models.BooleanField(default=False)),
                ('peut_creer', models.BooleanField(default=False)),
                ('peut_modifier', models.BooleanField(default=False)),
                ('peut_valider', models.BooleanField(default=False)),
                ('peut_supprimer', models.BooleanField(default=False)),
                ('peut_exporter', models.BooleanField(default=False)),
                ('peut_imprimer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type_role', models.CharField(choices=[('direction_generale', 'Direction Générale'), ('directeur_general', 'Directeur Général'), ('directeur_executif', 'Directeur Exécutif'), ('coordonnateur_programme', 'Coordonnateur Programme'), ('responsable_programme', 'Responsable Programme'), ('chef_projet', 'Chef Projet'), ('responsable_activite', 'Responsable Activité'), ('agent_terrain', 'Agent Terrain'), ('responsable_se', 'Responsable S&E'), ('analyste_se', 'Analyste S&E'), ('comptable', 'Comptable'), ('controleur_financier', 'Contrôleur Financier'), ('archiviste', 'Archiviste'), ('gestionnaire_ged', 'Gestionnaire GED'), ('administrateur', 'Administrateur'), ('super_administrateur', 'Super Administrateur'), ('personnalise', 'Rôle personnalisé')], default='personnalise', max_length=30)),
                ('est_systeme', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rôle',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Session utilisateur',
                'ordering': ['-created_at'],
            },
        ),
    ]
