# Generated by Django 6.0.5 on 2026-06-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='couleur',
            field=models.CharField(blank=True, default='#6366f1', max_length=7),
        ),
    ]
