# Generated by Django 6.0.5 on 2026-05-30 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planification', '0001_initial'),
        ('programmes_projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyseswot',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses_swot', to='programmes_projets.programme'),
        ),
        migrations.AddField(
            model_name='analyseswot',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses_swot', to='programmes_projets.projet'),
        ),
        migrations.AddField(
            model_name='cadrelogique',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadres_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cadrelogique',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadres_logiques', to='programmes_projets.programme'),
        ),
        migrations.AddField(
            model_name='cadrelogique',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadres_logiques', to='programmes_projets.projet'),
        ),
        migrations.AddField(
            model_name='cadrelogique',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadres_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elementcadrelogique',
            name='cadre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='planification.cadrelogique'),
        ),
        migrations.AddField(
            model_name='elementcadrelogique',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_elements', to='planification.elementcadrelogique'),
        ),
        migrations.AddField(
            model_name='activitepa',
            name='element_cadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_pa', to='planification.elementcadrelogique'),
        ),
        migrations.AddField(
            model_name='elementswot',
            name='analyse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='planification.analyseswot'),
        ),
        migrations.AddField(
            model_name='jalon',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jalons_planif', to='programmes_projets.projet'),
        ),
        migrations.AddField(
            model_name='planaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_action_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planaction',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans_action', to='programmes_projets.programme'),
        ),
        migrations.AddField(
            model_name='planaction',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans_action', to='programmes_projets.projet'),
        ),
        migrations.AddField(
            model_name='planaction',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_action_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionplanitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planification.planaction'),
        ),
        migrations.AddField(
            model_name='plantravail',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_travail', to='programmes_projets.projet'),
        ),
        migrations.AddField(
            model_name='plantravail',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_travail_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activite',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='planification.plantravail'),
        ),
        migrations.AddField(
            model_name='programmeactivites',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programmeactivites',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programmes_activites', to='programmes_projets.programme'),
        ),
        migrations.AddField(
            model_name='programmeactivites',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programmes_activites', to='programmes_projets.projet'),
        ),
        migrations.AddField(
            model_name='programmeactivites',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitepa',
            name='programme_activites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='planification.programmeactivites'),
        ),
        migrations.AddField(
            model_name='strategieswot',
            name='analyse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='planification.analyseswot'),
        ),
        migrations.AddField(
            model_name='strategieswot',
            name='elements_lies',
            field=models.ManyToManyField(blank=True, to='planification.elementswot'),
        ),
        migrations.AddField(
            model_name='tdr',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tdrs', to='programmes_projets.programme'),
        ),
        migrations.AddField(
            model_name='tdr',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tdrs', to='programmes_projets.projet'),
        ),
        migrations.AddField(
            model_name='tdr',
            name='publie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tdrs_publies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tdr',
            name='redige_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tdrs_rediges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tdr',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tdrs_valides', to=settings.AUTH_USER_MODEL),
        ),
    ]
