# Generated by Django 6.0.5 on 2026-05-30 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ged', '0001_initial'),
        ('programmes_projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_modele', models.CharField(choices=[('prevision_budget', 'Prévision budgétaire'), ('prevision_indicateur', 'Prévision indicateurs'), ('prevision_tresorerie', 'Prévision trésorerie'), ('prevision_livrable', 'Prévision livrables'), ('detection_anomalie', 'Détection des anomalies'), ('detection_retard', 'Détection des retards'), ('detection_fraude', 'Détection des fraudes potentielles'), ('recommandation', 'Recommandation stratégique')], max_length=25)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_entrainement', 'En entraînement')], default='actif', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('precision', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('parametres', models.JSONField(blank=True, default=dict)),
                ('derniere_execution', models.DateTimeField(blank=True, null=True)),
                ('nb_executions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modèle IA',
            },
        ),
        migrations.CreateModel(
            name='AnalyseIAPredictive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyse', models.CharField(choices=[('prevision_budget', 'Prévision budgétaire'), ('prevision_indicateur', 'Prévision indicateurs'), ('prevision_tresorerie', 'Prévision trésorerie'), ('prevision_livrable', 'Prévision livrables'), ('detection_anomalie', 'Détection des anomalies'), ('detection_retard', 'Détection des retards'), ('detection_fraude', 'Détection des fraudes potentielles'), ('recommandation', 'Recommandation stratégique')], max_length=25)),
                ('parametres', models.JSONField(blank=True, default=dict)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('complete', 'Complète'), ('erreur', 'Erreur')], default='en_attente', max_length=15)),
                ('resultats', models.JSONField(blank=True, default=dict)),
                ('previsions', models.JSONField(blank=True, default=list)),
                ('anomalies', models.JSONField(blank=True, default=list)),
                ('suggestions_ia', models.TextField(blank=True)),
                ('score_confiance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('demande_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_ia_demandees', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_ia_predictives', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_ia_predictives', to='programmes_projets.projet')),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='intelligence_artificielle.modeleia')),
            ],
            options={
                'verbose_name': 'Analyse IA prédictive',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlerteIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('retard_prevu', 'Retard prévu'), ('depassement_budget', 'Dépassement budgétaire prévu'), ('risque_identifie', 'Risque identifié'), ('anomalie', 'Anomalie détectée'), ('derive', 'Dérive détectée'), ('fraude_potentielle', 'Fraude potentielle')], max_length=25)),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critique', 'Critique')], default='warning', max_length=10)),
                ('titre', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('lue', models.BooleanField(default=False)),
                ('traitee', models.BooleanField(default=False)),
                ('date_alerte', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_ia', to=settings.AUTH_USER_MODEL)),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='intelligence_artificielle.analyseiapredictive')),
            ],
            options={
                'verbose_name': 'Alerte IA',
                'ordering': ['-date_alerte'],
            },
        ),
        migrations.CreateModel(
            name='ConversationIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('contexte', models.CharField(choices=[('general', 'Général'), ('projet', 'Projet'), ('budget', 'Budget'), ('indicateurs', 'Indicateurs S&E'), ('courriers', 'Courriers'), ('documents', 'Documents GED'), ('rapports', 'Rapports')], default='general', max_length=20)),
                ('archivee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_ia', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_ia', to='programmes_projets.projet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation IA',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('tdr', 'TDR (Termes de Référence)'), ('swot', 'Analyse SWOT'), ('cadre_logique', 'Cadre logique'), ('rapport_activites', "Rapport d'activités"), ('rapport_bailleur', 'Rapport bailleur'), ('compte_rendu', 'Compte rendu'), ('courrier', 'Courrier'), ('note_synthese', 'Note de synthèse'), ('plan_action', "Plan d'action"), ('rapport_se', 'Rapport S&E'), ('rapport_financier', 'Rapport financier')], max_length=20)),
                ('mode', models.CharField(choices=[('generation', 'Génération complète'), ('réécriture', 'Réécriture / Reformulation'), ('resume', 'Résumé'), ('traduction', 'Traduction'), ('correction', 'Correction')], default='generation', max_length=20)),
                ('titre', models.CharField(max_length=300)),
                ('langue', models.CharField(default='fr', max_length=10)),
                ('instructions', models.TextField(blank=True)),
                ('texte_source', models.TextField(blank=True)),
                ('parametres', models.JSONField(blank=True, default=dict)),
                ('contenu_genere', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de génération'), ('complete', 'Complète'), ('erreur', 'Erreur'), ('revise', 'En révision'), ('valide', 'Validé')], default='en_attente', max_length=15)),
                ('score_qualite', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tokens_utilises', models.IntegerField(default=0)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('demande_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations_documents', to=settings.AUTH_USER_MODEL)),
                ('document_ged', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations_ia', to='ged.document')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations_ia', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations_ia', to='programmes_projets.projet')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Génération documentaire IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('conversation', 'Conversation assistant'), ('generation', 'Génération documentaire'), ('analyse_predictive', 'Analyse prédictive'), ('alerte', 'Alerte IA'), ('recommandation', 'Recommandation'), ('classification', 'Classification automatique'), ('resume', 'Résumé automatique')], max_length=25)),
                ('objet_type', models.CharField(blank=True, max_length=50)),
                ('objet_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('parametres_entree', models.JSONField(blank=True, default=dict)),
                ('resultats_sortie', models.JSONField(blank=True, default=dict)),
                ('tokens_utilises', models.IntegerField(default=0)),
                ('duree_ms', models.IntegerField(default=0)),
                ('succes', models.BooleanField(default=True)),
                ('message_erreur', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant IA'), ('systeme', 'Système')], default='user', max_length=10)),
                ('contenu', models.TextField()),
                ('requete_metier', models.JSONField(blank=True, default=dict, help_text="Requête Django/SQL générée par l'IA")),
                ('donnees_contexte', models.JSONField(blank=True, default=dict)),
                ('tokens_utilises', models.IntegerField(default=0)),
                ('duree_traitement_ms', models.IntegerField(default=0)),
                ('confiance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='intelligence_artificielle.conversationia')),
            ],
            options={
                'verbose_name': 'Message IA',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommandationIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_recommandation', models.CharField(choices=[('action_corrective', 'Action corrective'), ('reallocation', 'Réallocation de ressources'), ('revision_calendrier', 'Révision du calendrier'), ('mitigation_risque', 'Mitigation de risque'), ('opportunite', "Saisie d'opportunité"), ('strategie', 'Recommandation stratégique')], max_length=25)),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('justification', models.TextField(blank=True)),
                ('impact_estime', models.TextField(blank=True)),
                ('priorite', models.IntegerField(default=3, help_text='1=Faible, 2=Moyenne, 3=Haute, 4=Critique')),
                ('statut', models.CharField(choices=[('proposee', 'Proposée'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée'), ('en_cours', 'En cours de mise en œuvre'), ('implementee', 'Implémentée')], default='proposee', max_length=20)),
                ('score_pertinence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acceptee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommandations_acceptees', to=settings.AUTH_USER_MODEL)),
                ('analyse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommandations', to='intelligence_artificielle.analyseiapredictive')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommandations_ia', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommandations_ia', to='programmes_projets.projet')),
            ],
            options={
                'verbose_name': 'Recommandation IA',
                'ordering': ['-priorite', '-created_at'],
            },
        ),
    ]
