# Generated by Django 6.0.5 on 2026-05-31 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programmes_projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoucheCartographique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_couche', models.CharField(choices=[('projets', 'Projets'), ('activites', 'Activités'), ('beneficiaires', 'Bénéficiaires'), ('partenaires', 'Partenaires'), ('infrastructures', 'Infrastructures'), ('risques', 'Risques'), ('indicateurs', 'Indicateurs S&E'), ('zones', 'Zones'), ('personnalisee', 'Couche personnalisée')], default='projets', max_length=20)),
                ('style_affichage', models.CharField(choices=[('points', 'Points'), ('lignes', 'Lignes'), ('polygones', 'Polygones'), ('heatmap', 'Heatmap'), ('cluster', 'Clusters')], default='points', max_length=15)),
                ('source_fond', models.CharField(choices=[('openstreetmap', 'OpenStreetMap'), ('google_maps', 'Google Maps'), ('satellite', 'Satellite'), ('terrain', 'Terrain'), ('custom', 'Personnalisée')], default='openstreetmap', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(default='#3388ff', max_length=7)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('opacite', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('est_visible', models.BooleanField(default=True)),
                ('est_publique', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=0)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couches_cartographiques', to=settings.AUTH_USER_MODEL)),
                ('filtre_programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmes_projets.programme')),
                ('filtre_projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmes_projets.projet')),
            ],
            options={
                'verbose_name': 'Couche cartographique',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CarteSIG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('centre_lat', models.DecimalField(decimal_places=6, default=5.3599, max_digits=9)),
                ('centre_lon', models.DecimalField(decimal_places=6, default=-4.0083, max_digits=9)),
                ('zoom_defaut', models.IntegerField(default=7)),
                ('est_publique', models.BooleanField(default=False)),
                ('est_defaut', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartes_sig_creees', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartes_sig', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartes_sig', to='programmes_projets.projet')),
                ('couches', models.ManyToManyField(blank=True, related_name='cartes', to='sig.couchecartographique')),
            ],
            options={
                'verbose_name': 'Carte SIG',
                'ordering': ['-est_defaut', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ZoneSIG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('type_zone', models.CharField(choices=[('pays', 'Pays'), ('region', 'Région'), ('departement', 'Département'), ('commune', 'Commune'), ('village', 'Village / Localité'), ('zone_intervention', "Zone d'intervention"), ('perimetre', 'Périmètre projet')], default='commune', max_length=25)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('superficie_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('latitude_centre', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude_centre', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geojson', models.JSONField(blank=True, default=dict, help_text='GeoJSON complet du polygone de la zone')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_zones', to='sig.zonesig')),
            ],
            options={
                'verbose_name': 'Zone SIG',
                'ordering': ['type_zone', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='PointCartographie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_point', models.CharField(choices=[('projet', 'Projet'), ('activite', 'Activité'), ('beneficiaire', 'Bénéficiaire'), ('infrastructure', 'Infrastructure'), ('partenaire', 'Partenaire'), ('collecte', 'Point de collecte'), ('risque', 'Risque'), ('ressource', 'Ressource')], default='projet', max_length=20)),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rayon_metres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valeur', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('unite', models.CharField(blank=True, max_length=50)),
                ('couleur', models.CharField(default='#3388ff', max_length=7)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('proprietes', models.JSONField(blank=True, default=dict)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sig/points/%Y/')),
                ('source_gps', models.CharField(blank=True, max_length=50)),
                ('precision_gps', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='sig.couchecartographique')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_carto_crees', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_sig_avances', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_sig_avances', to='programmes_projets.projet')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='sig.zonesig')),
            ],
            options={
                'verbose_name': 'Point cartographique',
                'ordering': ['type_point', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='InfrastructureSIG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_infrastructure', models.CharField(choices=[('ecole', 'École'), ('hopital', 'Hôpital / Centre de santé'), ('puits', 'Puits / Forage'), ('route', 'Route'), ('pont', 'Pont'), ('marche', 'Marché'), ('bureau', 'Bureau / Siège'), ('entrepot', 'Entrepôt'), ('autre', 'Autre')], default='bureau', max_length=15)),
                ('statut', models.CharField(choices=[('operationnel', 'Opérationnel'), ('en_construction', 'En construction'), ('en_renovation', 'En rénovation'), ('abandonne', 'Abandonné')], default='operationnel', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('capacite', models.IntegerField(blank=True, null=True)),
                ('population_beneficiaire', models.IntegerField(blank=True, null=True)),
                ('date_mise_en_service', models.DateField(blank=True, null=True)),
                ('cout_realisation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('proprietes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructures_creees', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructures_sig', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructures_sig', to='programmes_projets.projet')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructures', to='sig.zonesig')),
            ],
            options={
                'verbose_name': 'Infrastructure SIG',
                'ordering': ['type_infrastructure', 'nom'],
            },
        ),
    ]
