# Generated by Django 6.0.5 on 2026-05-30 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('sigle', models.CharField(blank=True, max_length=30)),
                ('type_organisation', models.CharField(choices=[('ong', 'ONG'), ('administration', 'Administration publique'), ('projet', 'Projet/Programme'), ('entreprise', 'Entreprise privée'), ('institution', 'Institution internationale')], max_length=20)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('dissoute', 'Dissoute')], default='active', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organisations/logos/')),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('numero_agrement', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('directeur_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations_dirigees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organisation',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=200)),
                ('sigle', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions_dirigees', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='gouvernance.organisation')),
            ],
            options={
                'verbose_name': 'Direction',
                'ordering': ['code'],
                'unique_together': {('organisation', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ComiteDirecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('date_tenue', models.DateTimeField()),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('programme', 'Programmé'), ('tenu', 'Tenu'), ('reporte', 'Reporté'), ('annule', 'Annulé')], default='programme', max_length=10)),
                ('ordre_du_jour', models.TextField(blank=True)),
                ('compte_rendu', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='comites_participant', to=settings.AUTH_USER_MODEL)),
                ('president', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comites_presides', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comites', to='gouvernance.organisation')),
            ],
            options={
                'verbose_name': 'Comité directeur',
                'ordering': ['-date_tenue'],
            },
        ),
        migrations.CreateModel(
            name='Bailleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('sigle', models.CharField(blank=True, max_length=30)),
                ('type_bailleur', models.CharField(choices=[('bilateral', 'Bilatéral'), ('multilateral', 'Multilatéral'), ('prive', 'Privé'), ('national', 'National/Gouvernemental'), ('fondation', 'Fondation')], max_length=15)),
                ('pays_origine', models.CharField(blank=True, max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('contact_nom', models.CharField(blank=True, max_length=200)),
                ('contact_fonction', models.CharField(blank=True, max_length=200)),
                ('contact_telephone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('exigences_reporting', models.TextField(blank=True)),
                ('conditions_financement', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bailleurs/logos/')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bailleurs', to='gouvernance.organisation')),
            ],
            options={
                'verbose_name': 'Bailleur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('sigle', models.CharField(blank=True, max_length=30)),
                ('type_partenaire', models.CharField(choices=[('ong', 'ONG'), ('ministere', 'Ministère'), ('bailleur', 'Bailleur de fonds'), ('prestataire', 'Prestataire'), ('entreprise_privee', 'Entreprise privée'), ('institution_internationale', 'Institution internationale'), ('collectivite', 'Collectivité territoriale'), ('autre', 'Autre')], max_length=30)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=15)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('contact_nom', models.CharField(blank=True, max_length=200)),
                ('contact_fonction', models.CharField(blank=True, max_length=200)),
                ('contact_telephone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('date_debut_partenariat', models.DateField(blank=True, null=True)),
                ('date_fin_partenariat', models.DateField(blank=True, null=True)),
                ('domaines_intervention', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partenaires', to='gouvernance.organisation')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=200)),
                ('type_site', models.CharField(choices=[('siege', 'Siège'), ('agence', 'Agence'), ('representation', 'Représentation régionale'), ('bureau_projet', 'Bureau de projet'), ('antenne', 'Antenne')], max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='gouvernance.organisation')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites_diriges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site',
                'ordering': ['type_site', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='SousDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_directions', to='gouvernance.direction')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_directions_dirigees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sous-direction',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('intitule', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='gouvernance.direction')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_diriges', to=settings.AUTH_USER_MODEL)),
                ('sous_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='gouvernance.sousdirection')),
            ],
            options={
                'verbose_name': 'Service',
                'ordering': ['code'],
            },
        ),
    ]
