# Generated by Django 6.0.5 on 2026-05-30 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programmes_projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteRecente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('document', 'Document modifié'), ('courrier', 'Courrier reçu'), ('livrable', 'Livrable validé'), ('tache', 'Tâche créée'), ('reunion', 'Réunion planifiée'), ('message', 'Message reçu'), ('budget', 'Budget modifié')], max_length=20)),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('lien', models.CharField(blank=True, max_length=500)),
                ('objet_type', models.CharField(blank=True, max_length=50)),
                ('objet_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_recentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité récente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_canal', models.CharField(choices=[('prive', 'Discussion privée'), ('groupe', 'Groupe'), ('projet', 'Canal projet'), ('programme', 'Canal programme'), ('direction', 'Canal direction')], default='groupe', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('est_prive', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canaux_crees', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canaux_messagerie', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canaux_messagerie', to='programmes_projets.projet')),
            ],
            options={
                'verbose_name': 'Canal messagerie',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='GroupeTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_groupe', models.CharField(choices=[('equipe_projet', 'Équipe projet'), ('comite_technique', 'Comité technique'), ('comite_pilotage', 'Comité de pilotage'), ('direction', 'Direction'), ('finance', 'Finance'), ('autre', 'Autre')], default='equipe_projet', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_crees', to=settings.AUTH_USER_MODEL)),
                ('membres', models.ManyToManyField(blank=True, related_name='groupes_travail', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_travail', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_travail', to='programmes_projets.projet')),
            ],
            options={
                'verbose_name': 'Groupe de travail',
            },
        ),
        migrations.CreateModel(
            name='MembreCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('membre', 'Membre'), ('observateur', 'Observateur')], default='membre', max_length=15)),
                ('rejoint_le', models.DateTimeField(auto_now_add=True)),
                ('dernier_lu', models.DateTimeField(blank=True, null=True)),
                ('notifications_actives', models.BooleanField(default=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='collaboration.canal')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships_canal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre canal',
                'unique_together': {('canal', 'utilisateur')},
            },
        ),
        migrations.AddField(
            model_name='canal',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='canaux_messagerie', through='collaboration.MembreCanal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_message', models.CharField(choices=[('texte', 'Texte'), ('fichier', 'Fichier'), ('image', 'Image'), ('systeme', 'Message système')], default='texte', max_length=10)),
                ('contenu', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='messagerie/%Y/%m/')),
                ('reactions', models.JSONField(blank=True, default=dict)),
                ('modifie', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='collaboration.canal')),
                ('en_reponse_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='collaboration.message')),
                ('mentions', models.ManyToManyField(blank=True, related_name='messages_mentionnes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('systeme', 'Système'), ('projet', 'Projet'), ('budget', 'Budget'), ('courrier', 'Courrier'), ('reunion', 'Réunion'), ('tache', 'Tâche'), ('livrable', 'Livrable'), ('document', 'Document'), ('message', 'Messagerie'), ('alerte', 'Alerte')], default='systeme', max_length=15)),
                ('titre', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('priorite', models.CharField(choices=[('normale', 'Normale'), ('haute', 'Haute'), ('critique', 'Critique')], default='normale', max_length=10)),
                ('canal', models.CharField(choices=[('interne', 'Interne (app)'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push mobile'), ('whatsapp', 'WhatsApp')], default='interne', max_length=15)),
                ('lue', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('lien', models.CharField(blank=True, max_length=500)),
                ('objet_type', models.CharField(blank=True, max_length=50)),
                ('objet_id', models.IntegerField(blank=True, null=True)),
                ('envoyee', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreferenceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_active', models.BooleanField(default=True)),
                ('sms_active', models.BooleanField(default=False)),
                ('push_active', models.BooleanField(default=True)),
                ('whatsapp_active', models.BooleanField(default=False)),
                ('types_actives', models.JSONField(blank=True, default=list)),
                ('heure_debut_silence', models.TimeField(blank=True, null=True)),
                ('heure_fin_silence', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférences notification',
            },
        ),
        migrations.CreateModel(
            name='LectureMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lu_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_lus', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='collaboration.message')),
            ],
            options={
                'unique_together': {('message', 'utilisateur')},
            },
        ),
    ]
