# Generated by Django 6.0.5 on 2026-05-31 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
        ('programmes_projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('type_evenement', models.CharField(choices=[('atelier', 'Atelier'), ('seminaire', 'Séminaire'), ('formation', 'Formation'), ('conference', 'Conférence'), ('forum', 'Forum'), ('mission', 'Mission terrain'), ('reunion', 'Réunion spéciale'), ('autre', 'Autre')], default='atelier', max_length=15)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('ouvert_inscriptions', 'Ouvert aux inscriptions'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('reporte', 'Reporté')], default='planifie', max_length=25)),
                ('description', models.TextField(blank=True)),
                ('objectifs', models.TextField(blank=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('lieu', models.CharField(blank=True, max_length=300)),
                ('adresse', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nb_participants_attendus', models.IntegerField(blank=True, null=True)),
                ('budget_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('budget_realise', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ordre_du_jour', models.TextField(blank=True)),
                ('compte_rendu', models.TextField(blank=True)),
                ('fichier_programme', models.FileField(blank=True, null=True, upload_to='evenements/programmes/%Y/')),
                ('fichier_compte_rendu', models.FileField(blank=True, null=True, upload_to='evenements/cr/%Y/')),
                ('est_public', models.BooleanField(default=False)),
                ('inscription_requise', models.BooleanField(default=True)),
                ('date_limite_inscription', models.DateField(blank=True, null=True)),
                ('lien_visio', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_organises', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='programmes_projets.projet')),
            ],
            options={
                'verbose_name': 'Événement',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='DepenseEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('hebergement', 'Hébergement'), ('restauration', 'Restauration'), ('transport', 'Transport'), ('location_salle', 'Location salle'), ('materiel', 'Matériel'), ('honoraires', 'Honoraires formateurs'), ('communication', 'Communication'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fournisseur', models.CharField(blank=True, max_length=200)),
                ('facture', models.FileField(blank=True, null=True, upload_to='evenements/depenses/%Y/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_evenements', to=settings.AUTH_USER_MODEL)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='collaboration.evenement')),
            ],
            options={
                'verbose_name': 'Dépense événement',
                'ordering': ['categorie'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_externe', models.CharField(blank=True, help_text='Pour les participants externes (non-utilisateurs)', max_length=200)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('confirme', 'Confirmé'), ('present', 'Présent'), ('absent', 'Absent'), ('annule', 'Annulé')], default='inscrit', max_length=10)),
                ('heure_arrivee', models.DateTimeField(blank=True, null=True)),
                ('heure_depart', models.DateTimeField(blank=True, null=True)),
                ('code_badge', models.CharField(blank=True, max_length=50)),
                ('qr_code_scan', models.BooleanField(default=False)),
                ('note_evaluation', models.IntegerField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='collaboration.evenement')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations_evenements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participant événement',
                'unique_together': {('evenement', 'utilisateur', 'email')},
            },
        ),
    ]
