# Generated by Django 6.0.5 on 2026-05-31 02:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ged', '0001_initial'),
        ('programmes_projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('sigle', models.CharField(blank=True, max_length=50)),
                ('type_partenaire', models.CharField(choices=[('ong', 'ONG'), ('bailleur', 'Bailleur de fonds'), ('institution_publique', 'Institution publique'), ('entreprise', 'Entreprise privée'), ('consultant', 'Cabinet / Consultant'), ('universite', 'Université / Recherche'), ('collectivite', 'Collectivité territoriale'), ('autre', 'Autre')], default='ong', max_length=25)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('potentiel', 'Potentiel')], default='actif', max_length=15)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('site_web', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('contact_principal', models.CharField(blank=True, max_length=200)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('telephone_contact', models.CharField(blank=True, max_length=30)),
                ('secteurs_intervention', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires/logos/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partenaires_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DepotDocumentPortail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(upload_to='portail/documents/%Y/%m/')),
                ('type_document', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=15)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depose_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots_portail', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots_portail', to='programmes_projets.projet')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots_valides', to=settings.AUTH_USER_MODEL)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots_documents', to='partenaires_bailleurs.partenaire')),
            ],
            options={
                'verbose_name': 'Dépôt document portail',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30)),
                ('intitule', models.CharField(max_length=300)),
                ('type_convention', models.CharField(choices=[('convention', 'Convention'), ('accord', 'Accord'), ('protocole', 'Protocole'), ('contrat', 'Contrat'), ('mou', 'Mémorandum (MoU)'), ('lettre_accord', "Lettre d'accord")], default='convention', max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_validation', 'En validation'), ('valide', 'Validé'), ('signe', 'Signé'), ('actif', 'Actif'), ('suspendu', 'Suspendu'), ('expire', 'Expiré'), ('resilie', 'Résilié'), ('archive', 'Archivé')], default='brouillon', max_length=15)),
                ('objet', models.TextField()),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('devise', models.CharField(default='XOF', max_length=5)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date_expiration_alerte', models.DateField(blank=True, help_text="Date pour déclencher l'alerte de renouvellement", null=True)),
                ('signataire_externe', models.CharField(blank=True, max_length=200)),
                ('clauses_principales', models.TextField(blank=True)),
                ('obligations_parties', models.TextField(blank=True)),
                ('conditions_renouvellement', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='conventions/%Y/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_ged', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions', to='ged.document')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions_partenaire', to='programmes_projets.programme')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions_partenaire', to='programmes_projets.projet')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions_suivies', to=settings.AUTH_USER_MODEL)),
                ('signataire_interne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions_signees', to=settings.AUTH_USER_MODEL)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conventions', to='partenaires_bailleurs.partenaire')),
            ],
            options={
                'verbose_name': 'Convention',
                'ordering': ['-date_signature', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('directeur', 'Directeur/Directrice'), ('coordinateur', 'Coordinateur/trice'), ('charge_programme', 'Chargé de programme'), ('financier', 'Responsable financier'), ('technique', 'Expert technique'), ('autre', 'Autre')], default='autre', max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('est_principal', models.BooleanField(default=False)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='partenaires_bailleurs.partenaire')),
            ],
            options={
                'verbose_name': 'Contact partenaire',
            },
        ),
        migrations.CreateModel(
            name='RenouvellementConvention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nouvelle_date_fin', models.DateField()),
                ('nouveau_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('motif', models.TextField(blank=True)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='conventions/renouvellements/%Y/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renouvellements', to='partenaires_bailleurs.convention')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renouvellements_conventions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Renouvellement convention',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiaisonProjetPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('bailleur_principal', 'Bailleur principal'), ('bailleur_secondaire', 'Bailleur secondaire'), ('partenaire_execution', "Partenaire d'exécution"), ('partenaire_technique', 'Partenaire technique'), ('sous_traitant', 'Sous-traitant')], default='partenaire_execution', max_length=25)),
                ('montant_finance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liaisons_partenaire', to='programmes_projets.projet')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liaisons_projet', to='partenaires_bailleurs.partenaire')),
            ],
            options={
                'verbose_name': 'Liaison projet-partenaire',
                'unique_together': {('partenaire', 'projet', 'role')},
            },
        ),
        migrations.CreateModel(
            name='AccesPortailPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_acces', models.CharField(choices=[('lecture', 'Lecture seule'), ('depot', 'Lecture + Dépôt documents'), ('interaction', 'Interaction complète')], default='lecture', max_length=15)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('expire', 'Expiré')], default='actif', max_length=10)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accorde_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acces_portail_accordes', to=settings.AUTH_USER_MODEL)),
                ('programmes_accessibles', models.ManyToManyField(blank=True, related_name='acces_portail', to='programmes_projets.programme')),
                ('projets_accessibles', models.ManyToManyField(blank=True, related_name='acces_portail', to='programmes_projets.projet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_portail_partenaire', to=settings.AUTH_USER_MODEL)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_portail', to='partenaires_bailleurs.partenaire')),
            ],
            options={
                'verbose_name': 'Accès portail partenaire',
                'unique_together': {('partenaire', 'utilisateur')},
            },
        ),
    ]
