# Generated by Django 6.0.5 on 2026-06-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_financiere', '0002_tresorerie_avancee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptebancaire',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('valide', 'Validé'), ('approuve', 'Approuvé'), ('en_cours', 'En cours'), ('liquide', 'Liquidé'), ('ordonnance', 'Ordonné'), ('paye', 'Payé'), ('annule', 'Annulé')], default='brouillon', max_length=15),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='type_engagement',
            field=models.CharField(choices=[('requisition', 'Réquisition'), ('demande_achat', "Demande d'achat"), ('bon_commande', 'Bon de commande'), ('contrat', 'Contrat'), ('engagement', 'Engagement budgétaire'), ('liquidation', 'Liquidation'), ('ordonnancement', 'Ordonnancement'), ('paiement', 'Paiement')], default='bon_commande', max_length=20),
        ),
        migrations.AlterField(
            model_name='mouvementbancaire',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rapprochementbancaire',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
