# Generated by Django 6.0.5 on 2026-05-31 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
        ('programmes_projets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportavancement',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_avancement', to='execution.mission'),
        ),
        migrations.AddField(
            model_name='rapportavancement',
            name='reunion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to='execution.reunion'),
        ),
        migrations.AddField(
            model_name='rapportavancement',
            name='tache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to='execution.tache'),
        ),
        migrations.AddField(
            model_name='rapportavancement',
            name='titre',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rapportavancement',
            name='type_objet',
            field=models.CharField(choices=[('projet', 'Rapport de projet'), ('tache', 'Rapport de tâche'), ('reunion', 'Rapport de réunion'), ('mission', 'Rapport de mission')], default='projet', max_length=10),
        ),
        migrations.AlterField(
            model_name='rapportavancement',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_avancement', to='programmes_projets.projet'),
        ),
    ]
