# Generated by Django 6.0.5 on 2026-06-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_intelligence', '0002_datamart_rh_courrier_ged_risque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamartcourrier',
            name='delai_traitement_moyen',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Délai moyen en jours', max_digits=8),
        ),
        migrations.AlterField(
            model_name='datamartcourrier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datamartged',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datamartrh',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datamartrisque',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
